name: weather_app
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter_localizations:
      sdk: flutter
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  intl: ^0.17.0   
  adaptive_theme: ^2.3.0
  http: ^0.13.4
  flutter_bloc: ^8.0.1
  get_it: ^7.2.0
  equatable: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/white/
    - assets/icons/blue/
    - assets/icons/
  #   - images/a_dot_ham.jpeg
  fonts:
    - family: RobotoSlab
      fonts:
        - asset: fonts/RobotoSlab-Bold.ttf
        - asset: fonts/RobotoSlab-Black.ttf
        - asset: fonts/RobotoSlab-ExtraBold.ttf
        - asset: fonts/RobotoSlab-ExtraLight.ttf
        - asset: fonts/RobotoSlab-Light.ttf
        - asset: fonts/RobotoSlab-Medium.ttf
        - asset: fonts/RobotoSlab-Regular.ttf
        - asset: fonts/RobotoSlab-SemiBold.ttf
        - asset: fonts/RobotoSlab-Thin.ttf
          style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
flutter_intl:
  enabled: true
